Fix environment usage
Signed-off-by: Henri Rosten <henri.rosten@unikie.com>

diff --git a/.github/workflows/test-ext-prs.yml b/.github/workflows/test-ext-prs.yml
--- a/.github/workflows/test-ext-prs.yml
+++ b/.github/workflows/test-ext-prs.yml
@@ -48,9 +48,10 @@ jobs:
     needs: authorize-without-approval
     runs-on: ubuntu-latest
     if: ${{ needs.authorize-without-approval.outputs.authorized_user == 'False' }}
-    environment: |
-      ${{ github.event_name == 'pull_request_target' &&
-          github.event.pull_request.head.repo.full_name != github.repository && 'external-build-workflow' }}
+    environment: 
+      ${{ ( github.event_name == 'pull_request_target' &&
+            github.event.pull_request.head.repo.full_name != github.repository && 
+            'external-build-workflow' ) || ( 'internal-build-workflow' ) }}
     steps:
       - name: Authorized external
         run: true
@@ -91,11 +92,13 @@ jobs:
 
           echo "Checking if workflow file is modified"
           workflow_changed='False'
+          workflow_filename=''
           while read -r line;
           do
             if [[ ${{ github.workflow_ref }} == *$line* ]]; then
-              echo "Change modifies this workflow file"
               workflow_changed='True'
+              workflow_filename="$line"
+              break
             fi
           done < <(git diff --name-only HEAD^ HEAD)
           echo "workflow_changed=$workflow_changed"
@@ -108,20 +111,24 @@ jobs:
              [ ${{ github.event.pull_request.head.repo.full_name }} != ${{ github.repository }} ];
           then
             echo ""
-            echo "::error::Editing this workflow file from an external PR is not allowed."
+            echo "::error::"\
+                  "Editing workflow file '$workflow_filename' with PR from a"\
+                  "forked repository is not allowed. The change you are trying to do"\
+                  "requires internal PR from someone with write access to this repo."
             exit 1
           fi
           echo ""
           echo "::error::"\
-               "Editing this workflow file from an internal PR is allowed. However,"\
-               "note the following: the change you have done for this workflow will"\
+               "You are editing workflow file '$workflow_filename' from an"\
+               "internal PR. Raising this error (but not failing the job) to make"\
+               "sure you understand that the workflow change you have done will"\
                "only take impact after merge."\
-               "Therefore, you need to manually test this change (perhaps in a"\
+               "Therefore, you need to manually test the change (perhaps in a"\
                "forked repo) before merge to make sure the change does not break"\
                "anything."\
                "For now, there's no point of running the remaining steps since the"\
-               "results would not reflect the change you have done to the workflow"\
-               "file, and might cause outright confusion or misinterpretation."
+               "results would not reflect the modification you have done to the"\
+               "workflow, and might cause outright confusion or misinterpretation."
 
   build:
     needs: [check-workflow-changes]
